# This workflow is used to build the project
name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: System Specs
        run: |
          lscpu
          free -h 
          lsblk
          
      - name: Build
        run: |
          cargo build
          cargo test

      - name: Bench
        run: |
          cargo bench

      - name: Test ffi example
        run: |
          bash examples/run.sh

          
          
          
