name: Build and Test Parallel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: System Specs
        run: |
          lscpu
          free -h
          lsblk

      - name: Build and Test
        run: |
          cargo build --verbose 
          cargo test --verbose


  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Bench
        run: cargo bench

  test-ffi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Test ffi example
        run: |
          bash examples/run.sh

  test-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test docker run
        run: |
          bash examples/run_in_docker.sh